### PR TITLE
NCCL-2.6.2 API change

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 06-Feb-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/f89a9ac1a9ce5277fb107ab3cf2ac403/raw/6bce6b7a54a9096bb50a0bd6ee6f544f1c542500/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/f89a9ac1a9ce5277fb107ab3cf2ac403/raw/12c6f0d41f85fd901b9ac969a5c6b98bc333a7f3/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/f89a9ac1a9ce5277fb107ab3cf2ac403/raw/ef96e5a29c2310eb0260579346f196a42e0ce33c/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 06-Feb-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/1febc6b0edb19cc57219282903811190/raw/a144f89696b486002371c35719835a04aafdd2dc/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/1febc6b0edb19cc57219282903811190/raw/b5987c5d16c01fa7fe0e10aaefcc99cd77f32416/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/1febc6b0edb19cc57219282903811190/raw/211a841cab83fafea8e2230060128da53a72e67d/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/1febc6b0edb19cc57219282903811190/raw/c5cd5a8b7685aa5aae4f8faf214e665460871861/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
