### PR TITLE
CI tester (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by artemry-mlnx**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 31-Aug-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/9ef73f462dfe54b873d81fd6221c9888/raw/7cd804b8c375318bf62aea9720a31b0a302f4d74/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/9ef73f462dfe54b873d81fd6221c9888/raw/ce5c4a84087b66474e456999fd75bbeeb70a862e/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 31-Aug-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/c563407978680b8fb32fce614b4209a4/raw/9035ed6f0912968001b907317202b23fbd27afde/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/c563407978680b8fb32fce614b4209a4/raw/c5f294f4af6e35324ce380f1b6e027eb88d884ac/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/c563407978680b8fb32fce614b4209a4/raw/36d401173c6743e55d1c5dab463435dc2601b4c9/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/c563407978680b8fb32fce614b4209a4/raw/518db119f2b091689b7ece474448f6f079254196/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
