### PR TITLE
ncclProd op is not supported with SHARP

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 26-Sep-2019

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/442c08eaa085dd005ad75085503cdce6/raw/9fff912e9d1155186bf9d45273a7dc7572f04389/configure_sharp_startup.log) | :x: FAIL
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/442c08eaa085dd005ad75085503cdce6/raw/9907119c89b3d2e704bd9968ba024b0bacdfaf01/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/442c08eaa085dd005ad75085503cdce6/raw/c6b508311d5a4affceae2566fa840d91cf6fa249/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bureddy** [comment]
@itemko Can you check if there is any issue in setup.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 26-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/8b9754b8170a4636767cb180fec8bae7/raw/f5e1545b473f5346cf9b50635e0f20843c585251/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/8b9754b8170a4636767cb180fec8bae7/raw/b458bcfcf792fd3fd13b34b123e570d5cb76cee1/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/8b9754b8170a4636767cb180fec8bae7/raw/6585b8176df7546dbc68769421dd9aff5ad8797f/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/8b9754b8170a4636767cb180fec8bae7/raw/f93aa29e078acff0d0773b1fddb1abdd040c9d71/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/8b9754b8170a4636767cb180fec8bae7/raw/fe86409e7d85ed408ecbe6676a7674d31596aed7/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by itemko** [comment]
@bureddy 
There were some issues with the IB switch - fixed after restart of the switch.

**Pull request merged**
