### PR TITLE
CI tester (do not merge)

### PR DESCRIPTION
**Pull request by artemry-mlnx**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/72cbc8a9f4bf9e378bfadc9998678839/raw/01078aa7ef61abc1c85ffa7d735e835853efa75f/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/72cbc8a9f4bf9e378bfadc9998678839/raw/78ae6b71903c16d17aaa00930c0cfca307b653a4/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/e0dbf0bd587fedec5afe721e8837a720/raw/0ce445c1093e988dfd32d3d09182021081d2bcbe/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/e0dbf0bd587fedec5afe721e8837a720/raw/ad72b7fe06f30d23912b6944ac0c3cbaeaf2fe24/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/d6dab5282d8d0b3ac28967ea1aa4de92/raw/afa2b6f5c3bf1adcaf374bf8b3cb472be161b510/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/d6dab5282d8d0b3ac28967ea1aa4de92/raw/20880082063f5dbfa3d974baaba4e20792f611a2/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/59d25f3f6846904e501285350932e31d/raw/bc207d7475ede30205abdc514386a4a4d103f160/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/59d25f3f6846904e501285350932e31d/raw/806af059b31ef9a3b6835e6786d90b56b006570e/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/e21326f35d2b93feca8bcee608588274/raw/ff00b5d9ee26eaa37d1dd2a44141edd5b291119c/configure_sharp_startup.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/e21326f35d2b93feca8bcee608588274/raw/5b8fc48127c20e4998ee034c66d0daac656d0742/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/e9b25e10ba92e75f5a53d08fd0d7e2ed/raw/e23479f33b71b891fe329f99095ebcb5ace8b2bc/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/e9b25e10ba92e75f5a53d08fd0d7e2ed/raw/938d3d256e995405f2b2d5f1069dd72e9317e560/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e9b25e10ba92e75f5a53d08fd0d7e2ed/raw/99e9e9ec1657d51926ad445b514fbdd4ab81b1ff/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 28-Jul-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/a9caa82ad6961e9be7dd3140a563d28e/raw/dbec67662f125543db87bc3f1cdcfc75a8fd8dd3/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/a9caa82ad6961e9be7dd3140a563d28e/raw/85cba6a8f5bcc34098045e73f099ba58c9f15119/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/a9caa82ad6961e9be7dd3140a563d28e/raw/7e0e41d20728c0a8dfebb5dcbc6949708055556d/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/a9caa82ad6961e9be7dd3140a563d28e/raw/2ffce82b86ca755b65fdda8ca9835e917a2c5303/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
