### PR TITLE
fix static_assert failure on older compilers

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 15-Jan-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/d10db7fcce6763146797f955f35479a9/raw/a6e4e4a609d2c7d1bf697145a2f50d16c52640b2/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/d10db7fcce6763146797f955f35479a9/raw/04515148b92f63b803bbb1bae55624c075456e00/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/d10db7fcce6763146797f955f35479a9/raw/84097048068b4ada5316eef35663f65de2d4e1d0/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/d10db7fcce6763146797f955f35479a9/raw/ed4c107cfad47695e3543e3126d7ed2ce0ae8a23/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by itemko** [comment]
@bureddy 
Which compiler version did raise such error?

**Comment by bureddy** [comment]
> @bureddy
> Which compiler version did raise such error?

@itemko  noticed that on 4.8.5 on MTR dgx setup

**Pull request merged**
