### PR TITLE
Exactmatch interface names

### PR DESCRIPTION
**Pull request by bureddy**
porting https://github.com/NVIDIA/nccl/pull/236

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

No log files, contact CI support

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bureddy** [comment]
@artemry-mlnx what is the reason for this CI issue?

**Comment by artemry-mlnx** [comment]
Need to align v1.x infra scripts with master - I'll do.

**Comment by artemry-mlnx** [comment]
It seems Mellanox:v1.x infra scripts are OK.
@bureddy you need to update .ci/ in bureddy:v1.x branch accordingly.

**Comment by bureddy** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

No log files, contact CI support

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bureddy** [comment]
@Sergei-Lebedev can you check the .CI failure in v1.x branch and also this fix to master

**Comment by Sergei-Lebedev** [comment]
cherry-picked ci changes from master in #33 
and applied this fix to master in #34 
@bureddy pls rebase this pr

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 18-May-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/1ee4e8d345d46dec549fa7d3b8ea9593/raw/2eb4ca43a82e1d1d25f3ceb5bce2f543bcb2f6c0/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/1ee4e8d345d46dec549fa7d3b8ea9593/raw/d764e3014ea3fee3710dbe2c9584f159b5afd56b/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/1ee4e8d345d46dec549fa7d3b8ea9593/raw/292e2cfd9d3e91bbe1faa49f90df1738bb7da963/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/1ee4e8d345d46dec549fa7d3b8ea9593/raw/8253e8a745e1c79045d2d5cc7b1cbe0a0d6004fe/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
