### PR TITLE
print plugin path in verbose

### PR DESCRIPTION
**Pull request by bureddy**
swx-dgx01:8861:8861 [0] NCCL INFO Plugin Path : /.autodirect/mtrswgwork/devendar/workspace/GIT/nccl-rdma-sharp-plugins/install/lib/libnccl-net.so

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Jun-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/ebb7a9b62fe6b3e87d78f54edf078159/raw/60c07803608cbf8287c5bfabfe0c9cbacda947f5/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/ebb7a9b62fe6b3e87d78f54edf078159/raw/706a67d88cb90264c5429b51bf9b8fcb8c16ea4d/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/ebb7a9b62fe6b3e87d78f54edf078159/raw/af825ab68d05e534304afefb96139308e38ad99f/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/ebb7a9b62fe6b3e87d78f54edf078159/raw/9e3c95af51a8247433ff4004098856a4403fb708/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by bureddy** [comment]
```
clx-host-21514:3612:3612 [0] NCCL INFO Plugin Path : /.autodirect/mtrswgwork/_ml_devops_team/workspace/ml-nccl-rdma-sharp-plugins-pr/158/nccl-rdma-sharp-plugins/lib/libnccl-net.so
clx-host-21514:3612:3612 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eno1:10.7.215.14<0>
```

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Jun-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/fac58eacb122e4df3922228868ad4694/raw/8b11bb1ce1dce54a7f84eefb54a98c2c5a4dc0a3/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/fac58eacb122e4df3922228868ad4694/raw/e473ad8734e8f77031b4ea6f95c656776bd3a7b3/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/fac58eacb122e4df3922228868ad4694/raw/1f7d4643fc2ecde6fa78924e5e49d6801edcf812/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/fac58eacb122e4df3922228868ad4694/raw/a91a6d2b6eb8bd887a157c6e775fef7166b107ff/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Jun-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/3bd57cbc0fb36dff5e05b1582b7a40e1/raw/df08c57365e5ad9b2e7d9ae55acf7384ecffac5f/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/3bd57cbc0fb36dff5e05b1582b7a40e1/raw/1ce746df7b6edb05963991dbf440f5d7c909d80f/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/3bd57cbc0fb36dff5e05b1582b7a40e1/raw/7ac56090031b40b3fbdd591e771223d3015c7ce0/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/3bd57cbc0fb36dff5e05b1582b7a40e1/raw/42065ef50407bf1ebeee400950102714136f9b94/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 12-Jun-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/b6cce0c739fe57a964f9d84ba40bb9bd/raw/1ef0725b3ba190a0fd09dc45b0fb74ed729a0636/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/b6cce0c739fe57a964f9d84ba40bb9bd/raw/78a413dd8706f7c72f5fa03d8b7a61ddd74d5318/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/b6cce0c739fe57a964f9d84ba40bb9bd/raw/25ec101e6531e1afe80b39b8be7f8e9836dd4af0/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/b6cce0c739fe57a964f9d84ba40bb9bd/raw/32060a47fdf026334e367d8b8e074afa00081c2c/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
