### PR TITLE
IB: port ar from nccl

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Aug-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/beaf45f11a7d434d7402d81c579f18d3/raw/396432610833e79c4a89971f774a06ca278d326e/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/beaf45f11a7d434d7402d81c579f18d3/raw/f99f271098c950c3a77fcf3f3d2b53dfe3af5a4c/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/beaf45f11a7d434d7402d81c579f18d3/raw/c90ea5ab725dc3c9030d5012d94268496ef1b287/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Aug-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/c2c4b35adca045756823f7c97d0d901c/raw/db545c0c9ffa74106f482fe3f77c5dfa7a011181/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/c2c4b35adca045756823f7c97d0d901c/raw/1806dba8836c3bb53297158790eaa5e992b076b3/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/c2c4b35adca045756823f7c97d0d901c/raw/6560ee77b5781c3aed2df220dbf4e2a31d273e36/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/c2c4b35adca045756823f7c97d0d901c/raw/6c808109245b3bd22c3d9fec6bc8146d3d44a96f/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
