### PR TITLE
Fixed the issue with NCCL-SHARP plugin loaded from HPC-X

### PR DESCRIPTION
**Pull request by itemko**
- Fixed the issue with NCCL-SHARP plugin loaded from HPC-X - CI used the NCCL plugin libraries from HPC-X instead of just built ones. 
- Added SHARP sanity tests with iallreduce.

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/731aaf8e3a622e375bb3b80081ac5fe3/raw/57a6db65dba5c82e987fa09403da8e0d87cca853/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/731aaf8e3a622e375bb3b80081ac5fe3/raw/091682b2a07acc407736f8d059fea43f8b1e467d/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/731aaf8e3a622e375bb3b80081ac5fe3/raw/415c1ddf5510005b03505a6fb0c2a7a918766867/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/731aaf8e3a622e375bb3b80081ac5fe3/raw/d1981ac402471543036c9d01b077f5e3f6be32f8/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/6d8e573c177a6da1663f1874f843dc6c/raw/4e1e9cc97adf785b316c1becb19d88daa71e7d37/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/6d8e573c177a6da1663f1874f843dc6c/raw/073f35a5ca28051e440d651a08b99e3240123148/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/6d8e573c177a6da1663f1874f843dc6c/raw/ac2764769003af6db42bcdad141acdb0d85f93ff/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/6d8e573c177a6da1663f1874f843dc6c/raw/ada4369214ea912dc8bf0e5e36236a4025811828/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/6d8e573c177a6da1663f1874f843dc6c/raw/49fc353351e366383da827f859be5719eb550823/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by bureddy** [comment]
@itemko how does this work when we add PR commits to the plugin?  Does it uses plugin from HPCX or one build with the PR?

**Comment by itemko** [comment]
@bureddy 
With current fix CI will use the plugin built from the PR commits (HPC-X plugin libs are removed from LD_LIBRARY_PATH).

**Comment by itemko** [comment]
SHARP libs are still used from HPC-X.
NCCL libs are built within CI from https://gitlab.com/Mellanox/nccl-sharp (master branch).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/952679f7622915099d9ef29bfcfa9b60/raw/e26323f2fbf7fc5149cdf937e857338bd5453d1d/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/952679f7622915099d9ef29bfcfa9b60/raw/bc959892d218746e42f54794da2912ec2747c912/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/952679f7622915099d9ef29bfcfa9b60/raw/1a778f8d1cb09de51d46570e0e803b2be55510d4/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/952679f7622915099d9ef29bfcfa9b60/raw/95b43b1fa7d3680c3170e13b0fb2fcf4148c3865/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/952679f7622915099d9ef29bfcfa9b60/raw/ad8c3fe7673f7a8e0602db2ea23b769c4597f413/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 18-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/7105fb70eebe00e2eb55360f0f82a165/raw/98950417f54c78dc36e9c5100e90afaa34fd21bf/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/7105fb70eebe00e2eb55360f0f82a165/raw/29977a8899a9a1925a25a6c017a4871d8f9e0d2c/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/7105fb70eebe00e2eb55360f0f82a165/raw/0b14558a5d3c779afe4b89699e1fff5a0f0430ed/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/7105fb70eebe00e2eb55360f0f82a165/raw/600de965afcfc97bce25e8e5d5b3d268a9b3278d/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by itemko** [comment]
Seems some issues with the IB switch - the switch is being restarted.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 18-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/ec252d5617c14c364d8e9be3c259107b/raw/fd1ccf27d3e97ff64f9cc0566db25c760aa3cde5/build_nccl.log) | :heavy_check_mark: PASS
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/ec252d5617c14c364d8e9be3c259107b/raw/f73c8aacf31b996e4d7e590567f09fd1cd093ce2/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/ec252d5617c14c364d8e9be3c259107b/raw/dd51381f9af7b8960c626fd6b075ba94a00ceb32/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/ec252d5617c14c364d8e9be3c259107b/raw/08563d14f8135dbde21754fe6a513ef2459ad933/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/ec252d5617c14c364d8e9be3c259107b/raw/033636646e9cc4b1f524aea7b5e2cbb0f647917d/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
