### PR TITLE
Integrate with Net API v4 ( NCCL-2.8.3)

### PR DESCRIPTION
**Pull request by bureddy**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 17-Nov-2020

Artefact file | Status
-- | --
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/861c8f4e3cde5bfceb4f7c898e0e7b4d/raw/5c2b4b179b8daecc5bf1cde612c482d61cb7b8c1/run_nccl_test.log) | :x: FAIL
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/861c8f4e3cde5bfceb4f7c898e0e7b4d/raw/a1f6dfa2321e31fdcf5b1c6c86483e67345b61bf/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/861c8f4e3cde5bfceb4f7c898e0e7b4d/raw/1097c21cb334173bd9366d7d6e834b08439cb8e4/configure_sharp_startup.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bureddy** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by bureddy** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 27-Nov-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/7300fe5358c2e7db9c11d6b4582dd136/raw/06a5dd239c5122749726fa0765c594952263276d/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/7300fe5358c2e7db9c11d6b4582dd136/raw/36a44c29380565d5cc50a2f43c0d5de8870fdcf5/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/7300fe5358c2e7db9c11d6b4582dd136/raw/320f8ab07e79d1988b6f007c8ceb8818b8a2209a/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/7300fe5358c2e7db9c11d6b4582dd136/raw/ae97deedd5cb7a38cb28933853f7ad1cb2a9f3ec/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
