### PR TITLE
CI tester (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by itemko**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/d84f906d0ffd4df0bf15d22424b3147c/raw/8a2ed8eb2e14a62801a73d16bab505badd79aa9c/build.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/2dc8ff6e89927bcf4b69573028c50321/raw/97bafd6cb1ebb71102092e5ab8ce111cb200b799/run_nccl_test.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/2dc8ff6e89927bcf4b69573028c50321/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/76237513bcf29078980580a21ce6e881/raw/97bafd6cb1ebb71102092e5ab8ce111cb200b799/run_nccl_test.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/76237513bcf29078980580a21ce6e881/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/5edc68f6cf8fb9b3ddbf3c2087d04d67/raw/88bf13d9698a4678d34d83c43e860e31c27c297e/run_nccl_test.log) | :x: FAIL
[build.log](https://gist.githubusercontent.com/mellanox-github/5edc68f6cf8fb9b3ddbf3c2087d04d67/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e69b4ffe9a9c10ed34d29d38e7019ae2/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e69b4ffe9a9c10ed34d29d38e7019ae2/raw/05c5799415630d2f6bb608780ad38471a6e17451/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/6c8a1075f06a82778741987bb7ecb6a1/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/6c8a1075f06a82778741987bb7ecb6a1/raw/a3f4af54810e9f7c2045f0bce18a5e7164a4ef2b/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/d3c7f9a606c00b1dfe7c0ac288f079f0/raw/d2ce7fa44407d88cd8c7dfc0715d89d7db5e1f2d/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/d3c7f9a606c00b1dfe7c0ac288f079f0/raw/3f8391465cd7274b14ee0b806179403b70b6d688/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/fab9d820268ef0ed214f31baa773272e/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/fab9d820268ef0ed214f31baa773272e/raw/e994a8957406b2e2b3217fdfda5d0c8c41604741/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/435c13f1ceef633cf6225744a9d59766/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/435c13f1ceef633cf6225744a9d59766/raw/42e2cd93c4f0686ce44082387b78bbbdee15e2b6/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/7c4ca77ee13f08f2b7015cd19c21b7b9/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/7c4ca77ee13f08f2b7015cd19c21b7b9/raw/7fd9936f3231201d2214eb47d87582f8b719896d/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/f55becac855531b2beb3ff01fb7cc2ac/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/f55becac855531b2beb3ff01fb7cc2ac/raw/4de7d5c034a75e5f174964f706f3b425c88ca6b9/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/48f011d08180df9d00a4a865e1cd69c7/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/48f011d08180df9d00a4a865e1cd69c7/raw/7469751ce2d2c8a2a689e4fd88ecbfb540975d69/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/90eac8f2f5792b118a4325212706fac0/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/90eac8f2f5792b118a4325212706fac0/raw/828de485976678342216e1289ba2cc1f48e1561d/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/b65ab572108449a703eae2618fa0d310/raw/1a956a1efe389385aacda2112fb4de35600afc46/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/b65ab572108449a703eae2618fa0d310/raw/2d6f203f69c8a520847e916a68d3a7f6eab4c1cd/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 23-Aug-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/5df320f51f47a0a0b60fe8d672cce5e5/raw/a292efa0dee54c9ba73fa8abc8f3b9a1e5b0b8a2/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/5df320f51f47a0a0b60fe8d672cce5e5/raw/2af5c50354adfe6743452572513dbf044b894191/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 02-Sep-2019

Artefact file | Status
-- | --

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 02-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/198bbd70010706e4d857f9fdded33db4/raw/2cada8cd05ededf1a4a4d741eabe08eb0a33e0fa/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 02-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/fbd7709e3c8bbe1e0ff80c30ffb101e4/raw/777019cfdf35dc897c333f67628b6aa47ac3565f/build.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/fbd7709e3c8bbe1e0ff80c30ffb101e4/raw/e6e5b8a6901afc9606afe003c9bf431ccd429f0e/run_nccl_test.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/fbd7709e3c8bbe1e0ff80c30ffb101e4/raw/3a0920fd7e85289fa457adcc183e41de94d1da67/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 02-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/855447429b8cf26a8115b897b1d8df1f/raw/777019cfdf35dc897c333f67628b6aa47ac3565f/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/855447429b8cf26a8115b897b1d8df1f/raw/34925ae6345335e6a056c31ea5b85f8e42539fbd/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/855447429b8cf26a8115b897b1d8df1f/raw/0085021156d9e804104a688c54e8117700e315b8/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/aa7cafa9393f9a23c29517b394b08820/raw/7f58d5a4cd4acbead11b6bddb3de0b20e5034f30/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/aa7cafa9393f9a23c29517b394b08820/raw/7a584463bdfbfe6ffd8af261cd67c47de3a0f2d6/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/aa7cafa9393f9a23c29517b394b08820/raw/9ea698b50a5041deb5eb1d1a40a83701ae8f9d3a/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e24b5bef3b5e61dc6c1df0d9524ffca6/raw/6a8636925ea3711d1ba67ecffc9dfc25e002b7b2/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e24b5bef3b5e61dc6c1df0d9524ffca6/raw/c66498a7c761fa6f408992c3241a5c4d680427c9/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e24b5bef3b5e61dc6c1df0d9524ffca6/raw/5acf2d3e3268fe5c8e9f90c081e3bbfb1717fd44/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/0b709ddb5df7ea10bacfecf0050edb08/raw/4dede573e351768c3883946e88bf6831e93c84d4/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 03-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/41555a4e1c2b50c6f0951fa06e543da2/raw/4dede573e351768c3883946e88bf6831e93c84d4/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 04-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/c848227bc03e573b40e81e2347321d25/raw/4dede573e351768c3883946e88bf6831e93c84d4/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 04-Sep-2019

Artefact file | Status
-- | --
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/cfebfbb6cb7e4624e02c140c8a3e41d1/raw/3f792c40d34228d8c8d139a1beb37ad0ccf2126c/build_nccl.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 04-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e51503fadf616fe2dd503fe1654e6afb/raw/867f2f0bd8239ecf4448b93f9065d62fe3bd8c84/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e51503fadf616fe2dd503fe1654e6afb/raw/201fdfd75805b87d9e566d91cc97668d97be6372/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e51503fadf616fe2dd503fe1654e6afb/raw/cc44a3f344df36cdb713e50c65dce2f2f80a04ff/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 04-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e9aceedb11179fd2257a20c2a20b04b6/raw/75c39486dcda7fff5bc525ce2a3db235f1d68f24/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e9aceedb11179fd2257a20c2a20b04b6/raw/b0ca38522bde50b579cff37b236c98acb150e70b/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e9aceedb11179fd2257a20c2a20b04b6/raw/ab83dfd1c4658bf3bfbfbe0d2adc9c8744d96b06/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 04-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/97f6b8e639c52c27f2436ca1b53fedfd/raw/75c39486dcda7fff5bc525ce2a3db235f1d68f24/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/97f6b8e639c52c27f2436ca1b53fedfd/raw/99944d3718fdcdc9cb94163e266b9f10c1b2cfe9/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/97f6b8e639c52c27f2436ca1b53fedfd/raw/2af5036c4c7ee5274a12976a9b945861af52dda3/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by itemko** [comment]
@mike-dubman 
> Maybe all emv section port to module file and load it from script. It will make pipeline smaller and script simpler. Wdyt?

I've removed redundant variables from the environment section. There're still some vars but mainly for the convenience.
Regarding to the pipeline simplification with modules as far as I see this is questionable - each time we will need to use such constructions to get env vars from module within Jenkinsfile:
> sh '''#!/bin/bash -l
>                 module load ml/ci-tools
>                 <script>
>                '''

**Comment by mike-dubman** [comment]
> @mike-dubman
> 
> > Maybe all emv section port to module file and load it from script. It will make pipeline smaller and script simpler. Wdyt?
> 
> I've removed redundant variables from the environment section. There're still some vars but mainly for the convenience.
> Regarding to the pipeline simplification with modules as far as I see this is questionable - each time we will need to use such constructions to get env vars from module within Jenkinsfile:
> 
> > sh '''#!/bin/bash -l
> > module load ml/ci-tools
> > <script>
> > '''

yep, but best to put ```module load ...``` into script itself.
by doing so - the script becomes only entrypoint from step into businesslogic and script becomes self-contained - you can run it from terminal shell for debug or repro w/o relaying on pipeline parts with env.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e6116bee16679594f2a735afdfcf6c3c/raw/7653e4d1807fa7fcb7313b079af3d7da99ee258d/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e6116bee16679594f2a735afdfcf6c3c/raw/f473cc9bb084fe0a691aa25341250cc3458a50bf/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e6116bee16679594f2a735afdfcf6c3c/raw/b2e570c785aee73875e8a69c3bc31f4dca8be7ca/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/42bb463d96763536ce616d9b7422752e/raw/926fa2dc1e6bfd15ed2601a88d2c7f430f09d2ef/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/42bb463d96763536ce616d9b7422752e/raw/d1ab936cd0738e9e21217fd478ee8f6c90500c87/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/42bb463d96763536ce616d9b7422752e/raw/ca425f83181a9fa7caa7fd9ccbad012000cf1b2a/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/73f71dcce92fc5d70eae97bc343edcac/raw/926fa2dc1e6bfd15ed2601a88d2c7f430f09d2ef/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/73f71dcce92fc5d70eae97bc343edcac/raw/8a5bf967f54d5fe21c52d2698b138d61e8629180/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/73f71dcce92fc5d70eae97bc343edcac/raw/9a6d4dc6c7f5a6000feb4cdcb37300cd9f74c488/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/02efc9ed56d6a0986cd11365d57c9bd2/raw/64a1c1cdef61ce87bdc5fbfef81f6baddc636d80/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/02efc9ed56d6a0986cd11365d57c9bd2/raw/e6807c5302b2b5072306988baa39ce82b1f6c562/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/02efc9ed56d6a0986cd11365d57c9bd2/raw/4506fd2b40ec4d418ef0fd6845e42748c95f589c/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

No log files, contact CI support

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/d334fb204213598be149c3dc74a45470/raw/ae329c43087b20abbd624b2d2ea2971a53e01103/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/d334fb204213598be149c3dc74a45470/raw/983a3b370a1f990242e20f7f3ccbc742c4f08607/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/d334fb204213598be149c3dc74a45470/raw/ee099e905382c8f28a453575ae295174f9d77971/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/85a2c4fbba22739a90c0c1efbe0afb67/raw/ae329c43087b20abbd624b2d2ea2971a53e01103/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/85a2c4fbba22739a90c0c1efbe0afb67/raw/19bf7641fcab7f280a34554c0949359c13493716/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/85a2c4fbba22739a90c0c1efbe0afb67/raw/095cd1efc84c7404ce537d4509b407b07539ad9a/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/f2508d7faa7e08b115cbeb1b21a20e31/raw/ae329c43087b20abbd624b2d2ea2971a53e01103/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/f2508d7faa7e08b115cbeb1b21a20e31/raw/54a77982f7a86bd60918712156c7496988e7614e/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/f2508d7faa7e08b115cbeb1b21a20e31/raw/cf8517fea6bc6c5b7749230356591738a46de272/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/e6594ecae7ebff84931f155ab282d0c9/raw/64a1c1cdef61ce87bdc5fbfef81f6baddc636d80/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/e6594ecae7ebff84931f155ab282d0c9/raw/e17496d99b3b0401702263436e99f8e66e386480/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/e6594ecae7ebff84931f155ab282d0c9/raw/1e60b8e5bdcb9fd4c9b6c2279ff5b578e98bf28f/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by itemko** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 05-Sep-2019

Artefact file | Status
-- | --
[build.log](https://gist.githubusercontent.com/mellanox-github/3673f23e6a257e879743f8c4b1b98d21/raw/ae329c43087b20abbd624b2d2ea2971a53e01103/build.log) | :heavy_check_mark: PASS
[build_nccl.log](https://gist.githubusercontent.com/mellanox-github/3673f23e6a257e879743f8c4b1b98d21/raw/abc282d6ebf5b7060ea6875bedc37b04be6b1262/build_nccl.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/3673f23e6a257e879743f8c4b1b98d21/raw/b296fd5e8687e9f91236680f9cd1ddeaa281a602/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
