### PR TITLE
CI tester (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by artemry-mlnx**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 07-Aug-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/231bef6a53cb29b2e831cad2a219f761/raw/2e4de0c202365ae6fea61bcf2277363646b0e6cd/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/231bef6a53cb29b2e831cad2a219f761/raw/0ab497440cfa35b15806ff7d3f30302bbf2abe51/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/231bef6a53cb29b2e831cad2a219f761/raw/c645cb0b4a021ab466251fc5388a4ef1e0a41f99/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by artemry-mlnx** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 07-Aug-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/ba93e05418b764f4665577b96569ba1e/raw/4bf5ee663774220a928920e0b078eb0af4f43fab/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/ba93e05418b764f4665577b96569ba1e/raw/0652793eb30890af0c15142f24cf8eaff4b6a1a6/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/ba93e05418b764f4665577b96569ba1e/raw/aac8ca3945233b1e47eedb3d1c2240355f5c8fc1/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/ba93e05418b764f4665577b96569ba1e/raw/dd4deaf6ff1cafd97433759e343eb245f591b585/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request closed without merging**
