### PR TITLE
UCX: cleanup rndv based plugin

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 07-Jul-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/eeb12d3d054dbc95d0860bb9ce55109d/raw/3b4251c851e51d8841065228309fba8617ca7082/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/eeb12d3d054dbc95d0860bb9ce55109d/raw/3447f8cb4286d13eb458d8db6949b9a1915a476c/configure_sharp_startup.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/eeb12d3d054dbc95d0860bb9ce55109d/raw/a419ab474ca0c225445bffe70525e81544e79218/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Mellanox CI FAILed.

**Comment by Sergei-Lebedev** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 07-Jul-2020

Artefact file | Status
-- | --
[build_nccl_rdma_sharp_plugins.log](https://gist.githubusercontent.com/mellanox-github/1007b2ff6119c19a2ca0dcde67a8b370/raw/799cebeef51eb3128904045e4c4870ce200a846e/build_nccl_rdma_sharp_plugins.log) | :heavy_check_mark: PASS
[configure_sharp_startup.log](https://gist.githubusercontent.com/mellanox-github/1007b2ff6119c19a2ca0dcde67a8b370/raw/da150f77b721ee78f335932770ea31dc4cd32e99/configure_sharp_startup.log) | :heavy_check_mark: PASS
[configure_sharp_stop.log](https://gist.githubusercontent.com/mellanox-github/1007b2ff6119c19a2ca0dcde67a8b370/raw/fc884a5ded10dd342500d43938c1e6fb09658e8d/configure_sharp_stop.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/1007b2ff6119c19a2ca0dcde67a8b370/raw/506a950a3cba6cb4d504a2b78477f06adf00421b/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
Mellanox CI PASSed.

**Pull request merged**
